/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nullfish_lib_vfs_impl_local_native_lib_NativeFileUtil */

#ifndef _Included_com_nullfish_lib_vfs_impl_local_native_lib_NativeFileUtil
#define _Included_com_nullfish_lib_vfs_impl_local_native_lib_NativeFileUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nullfish_lib_vfs_impl_local_native_lib_NativeFileUtil
 * Method:    listFile
 * Signature: (Ljava/lang/String;)Lcom/nullfish/lib/vfs/impl/local/native_lib/LocalFileInfo;
 */
JNIEXPORT jobject JNICALL Java_com_nullfish_lib_vfs_impl_local_native_1lib_NativeFileUtil_listFile
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
